# Generated by Django 3.2 on 2023-07-29 14:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название округа')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='контур округа')),
            ],
            options={
                'verbose_name': 'Округ',
                'verbose_name_plural': 'Округа',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название региона')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='контур региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название района')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='контур района')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_districts', to='geodata.region')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='контур')),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canton_contours', to='geodata.canton')),
            ],
        ),
        migrations.AddField(
            model_name='canton',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_cantons', to='geodata.district'),
        ),
    ]
